=== niranjanthapa6441/ValidationOfXMLFile/catalog_19031196.dtd
<!ELEMENT result (schoolInformation,Marksheet+)>
<!ELEMENT schoolInformation (school+)>
<!ATTLIST school schoolID ID #REQUIRED>
<!ELEMENT school (name,address,phoneNumber,email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT Marksheet (Examination,studentName,subjects,totalMarksObtained,percentage,division)>
<!ELEMENT Examination (#PCDATA)>
<!ATTLIST Examination examination  (Final|Pre-Board) #REQUIRED>
<!ATTLIST Examination level  (Secondary|Primary|LowerSecondary|HigherSecondary) #REQUIRED>
<!ELEMENT studentName (#PCDATA)>
<!ATTLIST studentName studentID ID #REQUIRED>
<!ATTLIST studentName schoolID IDREF #REQUIRED>
<!ATTLIST studentName gender  (Male|Female) #REQUIRED>
<!ATTLIST studentName age CDATA #REQUIRED>
<!ELEMENT subjects (subject+)>
<!ELEMENT subject (fullMarks,passMarks,marksObtained,remarks)>
<!ATTLIST subject subjectName  (Math|Science|Computer|Nepali) #REQUIRED>
<!ATTLIST subject subjectID  (MA1249|CMP2536|NEP1476|SCN1549) #REQUIRED>
<!ELEMENT fullMarks (#PCDATA)>
<!ELEMENT passMarks (#PCDATA)>
<!ELEMENT marksObtained (theory,practical?,total)>
<!ELEMENT theory (#PCDATA)>
<!ELEMENT practical (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT remarks (#PCDATA)>
<!ELEMENT totalMarksObtained (#PCDATA)>
<!ELEMENT percentage (#PCDATA)>
<!ELEMENT division (#PCDATA)>
<!ATTLIST division type  (Pass|Fail) #REQUIRED>

=== niranjanthapa6441/ValidationOfXMLFile/Catalog_19031196.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE result SYSTEM "catalog_19031196.dtd">
<result>
    <schoolInformation>
        <school schoolID="SAMV">
            <name>Sainik Awasiya Mahavidhyalaya</name>
            <address>Sallaghari,Bhaktapur</address>
            <phoneNumber>01-6623456</phoneNumber>
            <email>samv@gmail.com</email>
        </school>
        <school schoolID="SVI">
            <name>Siddhartha Vanasthali Institue</name>
            <address>Banasthali,Kathmandu</address>
            <phoneNumber>01-4885678</phoneNumber>
            <email>svi@gmail.com</email>
        </school>
    </schoolInformation>
    <Marksheet>
        <Examination examination="Final" level="LowerSecondary">District Level Examination</Examination>
        <studentName studentID="a765432" schoolID="SAMV" gender="Male" age="14">Niranjan Thapa</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>96</theory>
                    <total>96</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>50</theory>
                    <practical>45</practical>
                    <total>95</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>65</theory>
                    <total>65</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>67</theory>
                    <practical>24</practical>
                    <total>91</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
        </subjects>
        <totalMarksObtained>340</totalMarksObtained>
        <percentage>86.75%</percentage>
        <division type="Pass">Distinction</division>
    </Marksheet>
    <Marksheet>
        <Examination examination="Final" level="LowerSecondary">District Level Examination</Examination>
        <studentName studentID="a706543" schoolID="SVI" gender="Female" age="14">Arya Basnet</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>92</theory>
                    <total>92</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>40</theory>
                    <practical>45</practical>
                    <total>90</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>75</theory>
                    <total>75</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>62</theory>
                    <practical>24</practical>
                    <total>86</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
        </subjects>
        <totalMarksObtained>342</totalMarksObtained>
        <percentage>85.5%</percentage>
        <division type="Pass">Distinction</division>
    </Marksheet>
    <Marksheet>
        <Examination examination="Pre-Board" level="Primary">District Level Examination</Examination>
        <studentName studentID="a765462" schoolID="SAMV" gender="Male" age="10">Prashanna Thapa</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>86</theory>
                    <total>86</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>45</theory>
                    <practical>45</practical>
                    <total>90</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>79</theory>
                    <total>79</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>60</theory>
                    <practical>24</practical>
                    <total>84</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
        </subjects>
        <totalMarksObtained>12</totalMarksObtained>
        <percentage>83.3%</percentage>
        <division type="Pass">Distinction</division>
    </Marksheet>
    <Marksheet>
        <Examination examination="Pre-Board" level="Primary">District Level Examination</Examination>
        <studentName studentID="a76543" schoolID="SAMV" gender="Female" age="10">Jasmine Singh Thakuri</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>92</theory>
                    <total>92</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>40</theory>
                    <practical>45</practical>
                    <total>90</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>75</theory>
                    <total>75</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>62</theory>
                    <practical>24</practical>
                    <total>86</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
        </subjects>
        <totalMarksObtained>342</totalMarksObtained>
        <percentage>85.5%</percentage>
        <division type="Pass">Distinction</division>
    </Marksheet>
    <Marksheet>
        <Examination examination="Final" level="Secondary">S.L.C.</Examination>
        <studentName studentID="a705543" schoolID="SVI" gender="Female" age="16">Preeti Karki</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>39</theory>
                    <total>39</total>
                </marksObtained>
                <remarks>Fail</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>40</theory>
                    <practical>45</practical>
                    <total>90</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>75</theory>
                    <total>75</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>62</theory>
                    <practical>24</practical>
