=== niranjanthapa6441/ValidationOfXMLFile/Catalog_Flatcatalog_19031196.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="result">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="schoolInformation" />
                <xs:element ref="Marksheet" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="schoolInformation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="school" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="school">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" />
                <xs:element name="address" />
                <xs:element name="phoneNumber" />
                <xs:element ref="email" />
            </xs:sequence>
            <xs:attribute name="schoolID" type="xs:ID" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[^@]+@[^\.]+\..+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Marksheet">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Examination" />
                <xs:element ref="studentName" />
                <xs:element ref="subjects" />
                <xs:element ref="totalMarksObtained" />
                <xs:element name="percentage" type="xs:string"/>
                <xs:element ref="division" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Examination">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="examination" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Final" />
                                <xs:enumeration value="Pre-Board"></xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="level" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Secondary" />
                                <xs:enumeration value="LowerSecondary" />
                                <xs:enumeration value="HigherSecondary" />
                                <xs:enumeration value="Primary" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="studentName">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="studentID" type="xs:ID" use="required" />
                    <xs:attribute name="schoolID" type="xs:IDREF" use="required" />
                    <xs:attribute name="gender" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Male" />
                                <xs:enumeration value="Female" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="age" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:int">
                                <xs:minInclusive value="1" />
                                <xs:maxInclusive value="100" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="subjects">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="subject" minOccurs="4" maxOccurs="4" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="subject">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fullMarks" />
                <xs:element ref="passMarks" />
                <xs:element ref="marksObtained" />
                <xs:element ref="remarks" />
            </xs:sequence>
            <xs:attribute name="subjectName" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Math" />
                        <xs:enumeration value="Nepali" />
                        <xs:enumeration value="Science" />
                        <xs:enumeration value="Computer" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="subjectID" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="MA1249" />
                        <xs:enumeration value="NEP1476" />
                        <xs:enumeration value="CMP2536" />
                        <xs:enumeration value="SCN1549" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="fullMarks">
        <xs:simpleType>
            <xs:restriction base="xs:int">
                <xs:pattern value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="passMarks">
        <xs:simpleType>
            <xs:restriction base="xs:int">
                <xs:pattern value="40" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="remarks">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Pass"/>
                <xs:enumeration value="Fail"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="marksObtained">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="theory" type="xs:int"/>
                <xs:element name="practical" type="xs:int" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="total"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="total">
        <xs:simpleType>
            <xs:restriction base="xs:int">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="100"></xs:maxInclusive>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="totalMarksObtained">
        <xs:simpleType>
            <xs:restriction base="xs:int">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="400"></xs:maxInclusive>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="division">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Pass"/>
                                <xs:enumeration value="Fail"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== niranjanthapa6441/ValidationOfXMLFile/catalog_flatcatalog_19031196.xml
<?xml version="1.0" encoding="UTF-8"?>
<result xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_Flatcatalog_19031196.xsd">
    <schoolInformation>
        <school schoolID="SAMV">
            <name>Sainik Awasiya Mahavidhyalaya</name>
            <address>Sallaghari,Bhaktapur</address>
            <phoneNumber>01-6623456</phoneNumber>
            <email>samv@gmail.com</email>
        </school>
        <school schoolID="SVI">
            <name>Siddhartha Vanasthali Institue</name>
            <address>Banasthali,Kathmandu</address>
            <phoneNumber>01-4885678</phoneNumber>
            <email>svi@gmail.com</email>
        </school>
    </schoolInformation>
    <Marksheet>
        <Examination examination="Final" level="LowerSecondary">District Level Examination</Examination>
        <studentName studentID="a765432" schoolID="SAMV" gender="Male" age="14">Niranjan Thapa</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>96</theory>
                    <total>96</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>50</theory>
                    <practical>45</practical>
                    <total>95</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>65</theory>
                    <total>65</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>67</theory>
                    <practical>24</practical>
                    <total>91</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
        </subjects>
        <totalMarksObtained>340</totalMarksObtained>
        <percentage>86.75%</percentage>
        <division type="Pass">Distinction</division>
    </Marksheet>
    <Marksheet>
        <Examination examination="Final" level="LowerSecondary">District Level Examination</Examination>
        <studentName studentID="a706543" schoolID="SVI" gender="Female" age="14">Arya Basnet</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>92</theory>
                    <total>92</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>40</theory>
                    <practical>45</practical>
                    <total>90</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>75</theory>
                    <total>75</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>62</theory>
                    <practical>24</practical>
                    <total>86</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
        </subjects>
        <totalMarksObtained>342</totalMarksObtained>
        <percentage>85.5%</percentage>
        <division type="Pass">Distinction</division>
    </Marksheet>
    <Marksheet>
        <Examination examination="Pre-Board" level="Primary">District Level Examination</Examination>
        <studentName studentID="a765462" schoolID="SAMV" gender="Male" age="10">Prashanna Thapa</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>86</theory>
                    <total>86</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>45</theory>
                    <practical>45</practical>
                    <total>90</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>79</theory>
                    <total>79</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>60</theory>
                    <practical>24</practical>
                    <total>84</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
        </subjects>
        <totalMarksObtained>12</totalMarksObtained>
        <percentage>83.3%</percentage>
        <division type="Pass">Distinction</division>
    </Marksheet>
    <Marksheet>
        <Examination examination="Pre-Board" level="Primary">District Level Examination</Examination>
        <studentName studentID="a76543" schoolID="SAMV" gender="Female" age="10">Jasmine Singh Thakuri</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>92</theory>
                    <total>92</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>40</theory>
                    <practical>45</practical>
                    <total>90</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>75</theory>
                    <total>75</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>62</theory>
                    <practical>24</practical>
                    <total>86</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
        </subjects>
        <totalMarksObtained>342</totalMarksObtained>
        <percentage>85.5%</percentage>
        <division type="Pass">Distinction</division>
    </Marksheet>
    <Marksheet>
        <Examination examination="Final" level="Secondary">S.L.C.</Examination>
        <studentName studentID="a705543" schoolID="SVI" gender="Female" age="16">Preeti Karki</studentName>
        <subjects>
            <subject subjectName="Math" subjectID="MA1249">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>39</theory>
                    <total>39</total>
                </marksObtained>
                <remarks>Fail</remarks>
            </subject>
            <subject subjectName="Computer" subjectID="CMP2536">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>40</theory>
                    <practical>45</practical>
                    <total>90</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Nepali" subjectID="NEP1476">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
                    <theory>75</theory>
                    <total>75</total>
                </marksObtained>
                <remarks>Pass</remarks>
            </subject>
            <subject subjectName="Science" subjectID="SCN1549">
                <fullMarks>100</fullMarks>
                <passMarks>40</passMarks>
                <marksObtained>
